server:
  port: 9000
spring:
  application:
    name: doc-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos
    routes:
      - name: 认证服务nacos
        serviceName: auth-service
        location: /v2/api-docs
