spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/postgres?useUnicode=true&characterEncoding=utf-8&ssl=false&serverTimezone=Asia/Shanghai
      username: postgres
      password: 1234
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      remove-abandoned: true
      remove-abandoned-timeout: 60
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 15000
      min-evictable-idle-time-millis: 60000
      keep-alive: true
      aop-patterns:
        - "com.hxl.gsc.module.*.service.*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123456
        allow: 0.0.0.0/0
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.css,/druid/*"

  data:
    redis:
      host: 127.0.0.1
      password: ""
      database: 1
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 10
          min-idle: 1
          max-wait: 2000ms
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23lir3KsWWFaFLPhtE
            client-secret: 3e34988a71462aeaeb4c9a6a1aca079c9cf0f35d

jwt:
  secret: 1234567890123456789012345678901#
  access-token-expiration: 30m
  refresh-token-expiration: 30d
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lwd.gsc.module
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
